---
- name: "firewalld █ Add services to firewall's {{ slurm_firewall_zone | default('public') }} zone"
  firewalld:
    zone: "{{ slurm_firewall_zone | default('public') }}"
    port: "{{ slurm_slurmd_port }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when: 
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  tags:
    - firewall

- name: file █ Create service needed directory
  file:
    path: /etc/systemd/system/slurmd.service.d
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: template █ Generate service file set_controller.conf
  template:
    src: set_controller.conf.j2
    dest: /etc/systemd/system/slurmd.service.d/set_controller.conf
    owner: root
    group: root
    mode: 0644
  notify: systemd █ Reload systemd configuration
  tags:
    - template

- name: service █ Manage slurmd state
  service:
    name: slurmd
    enabled: yes
    state: started
  tags:
    - service

