---
- name: registry █ Create local directory
  file:
    path: "{{ podman_local_registry_dir }}"
    state: directory

- name: registry █ Check the path of the registry container
  stat:
    path: "{{ podman_registry_container_path }}"
  register: p

- name: registry █ Fail if path does not exist
  debug: 
    msg: "Path {{ podman_registry_container_path }} does not exists"
  fail_when: p.stat.isfile is not defined

- name: registry █ Run local registry
  shell: "podman load --privileged -d --name registry -p 5000:{{ podman_local_registry_port }} -v /var/lib/registry:{{ podman_local_registry_dir }} --restart=always -i {{ podman_registry_container_path }}"
