- name: systemd █ Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: service █ Restart bbautomate_flask service
  service:
    name: bbautomate_flask
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)

- name: service █ Restart bbautomate_celery service
  service:
    name: bbautomate_celery
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
