---
- name: set_fact ░ Gather exporters to install
  set_fact:
    exporters_groups: "{{ (exporters_groups | default([])) + item.value }}"
  loop: "{{ prometheus_exporters_groups_to_scrape | dict2items}}"
  when: inventory_hostname in groups[item.key]

- name: package █ install exporters packages
  package:
    name: "{{ item.package }}"
    state: present
  loop: "{{ exporters_groups }}"
  when: item.package is defined and item.package is not none

- name: "firewalld █ Open exporters ports into firewall's {{ prometheus_client_firewall_zone | default('public') }} zone"
  firewalld:
    zone: "{{ prometheus_client_firewall_zone | default('public') }}"
    port: "{{ item.port }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  loop: "{{ exporters_groups }}"
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
    - item.port is defined
  tags:
    - firewall

- name: service █ Manage exporters services
  service:
    name: "{{ item.service }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ exporters_groups }}"
  when: item.service is defined and item.service is not none
