---
- name: include_tasks ░ Prometheus client
  include_tasks: "client.yml"
  when: prometheus_client
  tags:
    - internal

- name: include_tasks ░ Prometheus server
  include_tasks: "server.yml"
  when: prometheus_server
  tags:
    - internal
