---

- name: stat ░ Check if file /etc/snmp_exporter/snmp.yml exist
  stat:
    path: /etc/snmp_exporter/snmp.yml
  register: prometheus_snmp_file_exist

- name: assert ░ Assert /etc/snmp_exporter/snmp.yml is present
  assert:
    that:
      - prometheus_snmp_file_exist.stat.exists
    fail_msg: |
      File /etc/snmp_exporter/snmp.yml is not present.
      Please refer to main documentation on how to generate this file, then
      re-execute this role.
      Exiting.
    success_msg: "/etc/snmp_exporter/snmp.yml is present, proceeding..."

- name: Package █ Install snmp_exporter package
  package:
    name: snmp_exporter
    state: present

# for generator of oid walk for snmp_exporter
- name: Package █ Install snmp_exporter generator packages
  package:
    name: "{{ item }}"
    state: present
  vars:
    packages:
    - gcc
    - make
    - net-snmp
    - net-snmp-utils
    - net-snmp-libs
    - net-snmp-devel
  when: prometheus_server_snmp_exporter_with_generator

- name: template █ Generate snmp_exporter service file
  template:
    src: snmp_exporter.service.j2
    dest: /etc/systemd/system/snmp_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: systemd █ Reload systemd configuration
  tags:
    - template

- name: file █ Create snmp_exporter directories structure
  file:
   path: "{{ item }}"
   state: directory
   mode: 0750
   owner: snmp_exporter
   group: snmp_exporter
  loop:
   - /etc/snmp_exporter/

- name: Template █ Generate /etc/snmp_exporter/snmp.yml
  template:
    src: snmp.yml.yml.j2
    dest: /etc/snmp_exporter/snmp.yml
    owner: snmp_exporter
    group: snmp_exporter
    mode: 0640
  when: prometheus_server_snmp_exporter_raw_configuration is defined and prometheus_server_snmp_exporter_raw_configuration is not none
  notify: service █ Restart snmp_exporter service
  tags:
    - template

- meta: flush_handlers

- name: stat ░ Check /etc/snmp_exporter/snmp.yml exists
  stat:
    path: /etc/snmp_exporter/snmp.yml
  register: stat_result

- name: assert ░ Assert that snmp.yml file exist
  assert:
    that:
      - stat_result.stat.exists
    fail_msg: "/etc/snmp_exporter/snmp.yml file does not exist, cannot start snmp_exporter"
    success_msg: "/etc/snmp_exporter/snmp.yml file does exist, proceeding"

- name: service █ Manage snmp_exporter service state
  service:
    name: snmp_exporter
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
