---
- name: Converge
  hosts: all
  any_errors_fatal: true
  vars:
    start_services: true
    enable_services: true
  tasks:
    - name: "Enable firewall for EL8"
      ansible.builtin.set_fact:
        ep_firewall: true
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "8"
        - ansible_facts.services['firewalld'] is defined

    - name: "Include grafana"
      ansible.builtin.include_role:
        name: "grafana"
      vars:
        - grafana_port: '9000'
        - grafana_api_url: 'http://127.0.0.1:9000'
