---
- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    - name: "Install firewalld and net-tools"
      ansible.builtin.package:
        name: "{{ item }}"
      when: ansible_facts.os_family == "RedHat"
      with_items:
        - firewalld
        - net-tools

    - name: "Start firewalld"
      ansible.builtin.service:
        name: firewalld
        state: started
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.services['firewalld'] is defined

    - name: "Configure Grafana repository for EL7/8"
      ansible.builtin.yum_repository:
        name: grafana
        description: Grafana repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: false
      when:
        - ansible_facts.os_family == "RedHat"
        # - ansible_facts.distribution_major_version == "7"
