---
- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    - name: "Install {{ item }}"
      package:
        name: "{{ item }}"
      when: ansible_facts.os_family == "RedHat"
      with_items:
        - firewalld
        - net-tools

    - name: "Start firewalld"
      service:
        name: firewalld
        state: started
      when: 
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.services['firewalld'] is defined

    - name: "Configure Grafana repository for EL7"
      yum_repository:
        name: grafana
        description: Grafana repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: False
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "7"
