---
- name: restart podman
  service:
    name: "{{ item  }}"
    state: restarted
    daemon_reload: true
  with_items: "{{ podman_services_to_start }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
